<?php
/**
 * Product view template
 *
 * @var $this Mage_Catalog_Block_Product_View
 */
?>
<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="product-view quick-view-window">
	<h2 class="subtitle-product"><?php echo $this->__('Quick View') ?></h2>
	<div class="product-essential">

		<?php echo $this->getBlockHtml('formkey') ?>
		<div class="no-display">
			<input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
			<input type="hidden" name="related_product" id="related-products-field" value="" />
		</div>

		<div class="product-shop">
			<div class="product-name">
				<h4><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h4>
			</div>

			<?php echo $this->getChildHtml('product_type_data') ?>

			<?php if ($this->canEmailToFriend()): ?>
				<p class="email-friend" style="display: none;"><a href="<?php echo $this->helper('catalog/product')->getEmailToFriendUrl($_product) ?>"><?php echo $this->__('Email to a Friend') ?></a></p>
			<?php endif; ?>

			<?php echo $this->getTierPriceHtml() ?>
			<?php echo $this->getChildHtml('extrahint') ?>

			<?php if ($_product->getShortDescription()):?>
				<div class="short-description">
					<h2><?php echo $this->__('Quick Overview') ?></h2>
					<div class="std"><?php echo $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description') ?></div>
				</div>
			<?php endif;?>

			<?php echo $this->getChildHtml('other');?>

			<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="button more link-learn"><?php echo $this->__('Learn More') ?></a>

		</div>

		<div class="product-img-box">
			<?php echo $this->getChildHtml('media') ?>
		</div>

		<div class="clearer"></div>

	</div>
</div>